namespace MirrorM.Common
{
    public enum SqlFieldType
    {
        Bigint = 1,
        Bigserial = 2,
        Bit = 3,
        BitVarying = 4,
        Boolean = 5,
        Box = 6,
        Bytea = 7,
        Character = 8,
        CharacterVarying = 9,
        Cidr = 10,
        Circle = 11,
        Date = 12,
        DoublePrecision = 13,
        Inet = 14,
        Integer = 15,
        Interval = 16,
        Json = 17,
        Jsonb = 18,
        Line = 19,
        Lseg = 20,
        Macaddr = 21,
        Macaddr8 = 22,
        Money = 23,
        Numeric = 24,
        Path = 25,
        Point = 26,
        Polygon = 27,
        Real = 28,
        Smallint = 29,
        Smallserial = 30,
        Serial = 31,
        Text = 32,
        Time = 33,
        TimeWithTimeZone = 34,
        Timestamp = 35,
        TimestampWithTimeZone = 36,
        Tsquery = 37,
        Tsvector = 38,
        Uuid = 39,
        Xml = 40,
    }
}
